# Generated by Django 3.1.5 on 2021-01-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_title'),
        ('accounts', '0003_auto_20210111_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watch_list',
            field=models.ManyToManyField(related_name='profile_watch_list', to='movies.Movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='watched_list',
            field=models.ManyToManyField(related_name='profile_watched_list', to='movies.Movie'),
        ),
    ]
