# Generated by Django 3.1.5 on 2021-01-12 18:17

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210112_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customaccount',
            name='username',
            field=models.CharField(error_messages={}, help_text='Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_ apenas.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator], verbose_name='usuário'),
        ),
    ]
