# Generated by Django 3.1.5 on 2021-01-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_title'),
        ('accounts', '0010_auto_20210112_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='watch_list',
            field=models.ManyToManyField(blank=True, related_name='profile_watch_list', to='movies.Movie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watched_list',
            field=models.ManyToManyField(blank=True, related_name='profile_watched_list', to='movies.Movie'),
        ),
    ]
